/*******************************************************************************
	Generated by: DLL to C version 3.78
	Date: 2021-4-6
	Description: The declaration of functions and variables for zeer.dll.
	Website: http://www.dll-decompiler.com
	Technical Support: support@dll-decompiler.com
*******************************************************************************/

#if !defined(_ZEER_SUPP_H_003C6000_INCLUDED_)
#define _ZEER_SUPP_H_003C6000_INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000


#include <windows.h>

#pragma pack(push)
#pragma pack(1)

__declspec(align(16)) struct stZeer
{
	UCHAR Header[0x1000];
	UCHAR Text[0x1000];
	UCHAR Rdata[0x1000];
	UCHAR Data[0x2000];
	UCHAR Rsrc[0x1000];
	UCHAR Reloc[0x1000];
	UCHAR PE[0x3BF000];
};

#pragma pack(pop)

__declspec(align(16)) extern stZeer Zeer;

/* Data for initialization. */
extern UCHAR Zeer_InitData[0x5BE];

extern HMODULE g_hZeer;

/*
	Description: Access any address in the DLL.
	Parameters:
		rvaAddr: The RVA address you want to access.
*/
void* __stdcall Zeer_RVA(DWORD rvaAddr);

#define Zeer_VA(vaAddr) Zeer_RVA((vaAddr) - 0x10000000)


#endif // !defined(_ZEER_SUPP_H_003C6000_INCLUDED_)